project:
  type: website
  output-dir: docs

css:
  - https://lalten.github.io/lmweb/style/latinmodern-roman.css
  - https://lalten.github.io/lmweb/style/latinmodern-sans.css
  - https://lalten.github.io/lmweb/style/latinmodern-mono.css

mainfont: "Latin Modern Sans"
fontsize: 15pt
fontfamilyoptions: "oblique"
monofont: "Latin Modern Mono"
highlight-style: "tango"

website:
  title: "BS Degree Notes"
  sidebar:
    collapse-level: 1
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Deep Learning"
        contents: 
          - href: pages/DL/Week01_1.md
            text: Week 1.1
          - href: pages/DL/Week01_2.md
            text: Week 1.2
          - href: pages/DL/Week02.md
            text: Week 2
          - href: pages/DL/Week03.md
            text: Week 3
          - href: pages/DL/Week04.md
            text: Week 4
          - href: pages/DL/Week05.md
            text: Week 5
          - href: pages/DL/Week06.md
            text: Week 6
      - section: "AI: Search Methods"
        contents: 
          - href: pages/AI/Week01.md
            text: Week 1
          - href: pages/AI/Week02.md
            text: Week 2
          - href: pages/AI/Week03.md
            text: Week 3
          - href: pages/AI/Week04.md
            text: Week 4
          - href: pages/AI/Week05.md
            text: Week 5
          - href: pages/AI/Week06.md
            text: Week 6
      - section: "Software Testing"
        contents: 
          - href: pages/ST/Week01.md
            text: Week 1
          - href: pages/ST/Week02.md
            text: Week 2
          - href: pages/ST/Week03.md
            text: Week 3
          - href: pages/ST/Week04.md
            text: Week 4
          - href: pages/ST/Week05.md
            text: Week 5
          - href: pages/ST/Week06.md
            text: Week 6
          - href: pages/ST/Week07.md
            text: Week 7
          - href: pages/ST/Week08.md
            text: Week 8
          - href: pages/ST/Week09.md
            text: Week 9
          - href: pages/ST/Week10.md
            text: Week 10
          - href: pages/ST/Week11.md
            text: Week 11
          - href: pages/ST/Week12.md
            text: Week 12
      - section: "Software Engineering"
        contents: 
          - href: pages/SE/Week01.md
            text: Week 1
          - href: pages/SE/Week02.md
            text: Week 2
          - href: pages/SE/Week03.md
            text: Week 3
          - href: pages/SE/Week04.md
            text: Week 4
          - href: pages/SE/Week09.md
            text: Week 9
          - href: pages/SE/Week10.md
            text: Week 10
          - href: pages/SE/Week11.md
            text: Week 11
      - section: "Reinforcement Learning"
        contents: 
          - href: pages/RL/Week01_1.md
            text: Week 1.1
          - href: pages/RL/Week01_2.md
            text: Week 1.2
          - href: pages/RL/Week02.md
            text: Week 2
      - section: "NLP"
        contents:
          - href: pages/NLP/Week01.md
            text: Week 1
      - section: "LLM"
        contents:
          - href: pages/LLM/Week01.md
            text: Week 1
format:
  html:
    theme: 
      light: [zephyr, styles_light.scss]
      dark: [darkly, styles.scss]
    toc: true
